// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzlhznoqpxxxceojevpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6bGh6bm9xcHh4eGNlb2pldnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0ODEzMjcsImV4cCI6MjA1NzA1NzMyN30.ai8aZ59anFlhaGuyBuSSVLmtbu_adExpRcioJiYORkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);