// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goyyyvvhcvhqamizinup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdveXl5dnZoY3ZocWFtaXppbnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNDAzMTEsImV4cCI6MjA1NjgxNjMxMX0.MQW3NK9IULUDlKLk02TRGZJBQ1NIHvUFvnuDR_SnXQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);